---
title: "Minto Pike Mark-Recapture - summary"
output: word_document
date: "2025-08-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, dpi=300, fig.width = 7, fig.height = 7)
```

```{r, message=FALSE, results='hide', warning=FALSE}
library(tidyverse)
library(janitor)
library(recapr)
library(dsftools)
library(knitr)

# loading some helper functions
source("FDS_2025/R/recapr_prep.R")

# reading raw data
event1_raw <- read_csv("FDS_2025/flat_data/event1.csv", skip=1) %>%
  remove_empty() %>%
  filter(!is.na(Unique)) %>%
  mutate(`Tag Number` = as.character(`Tag Number`)) %>%
  rename(FL = `Fork Length (mm)`)
event2_raw <- read_csv("FDS_2025/flat_data/event2.csv", skip=1) %>%
  remove_empty() %>%
  filter(!is.na(Unique)) %>%
  mutate(`Tag Number` = as.character(`Tag Number`)) %>%
  rename(FL = `Fork Length (mm)`) %>%
  rename(FLc = `Fork Length Corrected (mm)`) %>%
  mutate(gear = sapply(strsplit(Comments, split="Gear= "), "[", 2)) %>%
  mutate(gear = factor(ifelse(gear=="G", "GN", gear)))

# creating truncated data tables
# c for corrected (length correction)
event1_550 <- event1_raw %>%
  filter(FL >= 550)
event2_550 <- event2_raw %>%
  filter(FL >= 550)
event2_550c <- event2_raw %>%
  filter(FLc >= 550)
event1_600 <- event1_raw %>%
  filter(FL >= 600)
event2_600 <- event2_raw %>%
  filter(FL >= 600)
event2_600c <- event2_raw %>%
  filter(FLc >= 600)


# creating MR objects from recapr_prep
mr550 <- recapr_prep(ID="Tag Number", event1=event1_550, event2=event2_550)
mr600 <- recapr_prep(ID="Tag Number", event1=event1_600, event2=event2_600)
mr550c <- recapr_prep(ID="Tag Number", event1=event1_550, event2=event2_550c)
mr600c <- recapr_prep(ID="Tag Number", event1=event1_600, event2=event2_600c)

# creating stratified MR objects (all possible ways)
mr550_strat <- stratify(mr550,
                        event_names = c("event1", "event2"),
                        column_names = c("FL","FL"),
                        breaks = c(550, 650, 1200))
mr600_strat <- stratify(mr600,
                        event_names = c("event1", "event2"),
                        column_names = c("FL","FL"),
                        breaks = c(600, 650, 1200))
mr550c_strat <- stratify(mr550c,
                        event_names = c("event1", "event2"),
                        column_names = c("FL","FLc"),
                        breaks = c(550, 650, 1200))
mr600c_strat <- stratify(mr600c,
                        event_names = c("event1", "event2"),
                        column_names = c("FL","FLc"),
                        breaks = c(600, 650, 1200))
```

## Overview

```{r}
n1 <- table(mr550_strat$input_data$event1$FL_strat)
n2 <- table(mr550_strat$input_data$event2$FL_strat)
m2_1 <- table(mr550_strat$recaps$matched$FL_strat_event1)
m2_2 <- table(mr550_strat$recaps$matched$FL_strat_event2)
```

which dataset and why, which stratification and why

tabulate n1, n2, m2 by stratum

## KS tests

```{r, fig.width=9, fig.height=4}
par(family="serif")
par(mfrow=c(1,2))
with(mr550_strat,
     ksplot(input_data$event1$FL,
            recaps$matched$FL_event1,
            col=c(1,2), legend=c("Event 1", "Recaps"), main="All samples"))
with(mr550_strat,
     ksplot(input_data$event2$FL,
            recaps$matched$FL_event2,
            col=c(1,4), legend=c("Event 2", "Recaps"), main="All samples"))

with(mr550_strat,
     ksplot(input_data$event1$FL %s_l% 650,
            recaps$matched$FL_event1 %s_l% 650,
            col=c(1,2), legend=c("Event 1", "Recaps"), main="550 - 649 mm"))
with(mr550_strat,
     ksplot(input_data$event2$FL %s_l% 650,
            recaps$matched$FL_event2 %s_l% 650,
            col=c(1,4), legend=c("Event 2", "Recaps"), main="550 - 649 mm"))
with(mr550_strat,
     ksplot(input_data$event1$FL %s_geq% 650,
            recaps$matched$FL_event1 %s_geq% 650,
            col=c(1,2), legend=c("Event 1", "Recaps"), main="650 mm +"))
with(mr550_strat,
     ksplot(input_data$event2$FL %s_geq% 650,
            recaps$matched$FL_event2 %s_geq% 650,
            col=c(1,4), legend=c("Event 2", "Recaps"), main="650 mm +"))
```

## Abundance Estimates & Length Composition

```{r}
Nhat_vec <- NChapman(n1, n2, m2_1)
seNhat_vec <-   seChapman(n1, n2, m2_1)
Nhat_strat <- Nstrat(n1, n2, m2_1)
seNhat_strat <- sestrat(n1, n2, m2_1)
```

don't forget to use ASL_boilerplate

```{r}
lengthbreaks <- c(550, 600, 650, 700, 800, 900, 1000, 1200) #550 to 1146
ASL_table(age = cut(mr550_strat$input_data$event2$FL, breaks=lengthbreaks, right=FALSE, 
                    dig.lab = 4),
          stratum=as.numeric(mr550_strat$input_data$event2$FL_strat),
          Nhat=as.numeric(Nhat_vec),
          se_Nhat = as.numeric(seNhat_vec)) %>% kable
## ^^^ fix digits and try to add commas ##############################
```

```{r, results='asis'}
ASL_boilerplate(age = cut(mr550_strat$input_data$event2$FL, breaks=lengthbreaks, 
                          right=FALSE, dig.lab = 4),
          stratum=as.numeric(mr550_strat$input_data$event2$FL_strat),
          Nhat=as.numeric(Nhat_vec),
          se_Nhat = as.numeric(seNhat_vec),
          species="pike")
## ^^^ I NEED to figure out how to have ASL_ deal with length as categorical!!!
```

## Capture gear

## Effects of length correction (or not) on inferences
